FROM scaleout/soss:latest
COPY sp_2.txt /usr/local/soss5/soss_params.txt
COPY scp_2.txt /usr/local/soss/soss_client_params.txt
WORKDIR /usr/local/soss5
ENTRYPOINT ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]